definitions:
  handler.ChatAutoBindCalendarParam:
    properties:
      enable:
        description: 功能启用
        type: boolean
      project_key:
        type: string
      work_item_id:
        type: integer
      work_item_type_key:
        type: string
    type: object
  handler.ErrMsgResp:
    properties:
      msg:
        type: string
    type: object
  handler.GetAutoBindCalendarStatusResp:
    properties:
      enable:
        type: boolean
    type: object
  handler.ListWorkItemMeetingsResp:
    properties:
      meetings:
        items:
          $ref: '#/definitions/handler.WorkItemMeeting'
        type: array
      total:
        type: integer
    type: object
  handler.MeegoUserInfo:
    properties:
      avatar_url:
        description: 头像链接
        type: string
      email:
        description: 邮箱
        type: string
      meego_user_key:
        description: Meego 的UserKey
        type: string
      name_cn:
        description: 中文名
        type: string
      name_en:
        description: 英文名
        type: string
    type: object
  handler.MeetingTime:
    properties:
      create_time:
        description: 创建时间
        type: string
      end_time:
        description: 结束时间
        type: string
      start_time:
        description: 开始时间
        type: string
    type: object
  handler.OperateCalendarEventWithWorkItemParam:
    properties:
      calendar_event_id:
        description: 日程 ID
        type: string
      calendar_id:
        description: 日历 ID
        type: string
      meeting_id:
        description: 会议 id (解绑的时候使用)
        type: string
      project_key:
        type: string
      with_after_recurring_event:
        description: 处理之后的重复日程 (解绑的时候使用)
        type: boolean
      work_item_id:
        type: integer
      work_item_type_key:
        type: string
    type: object
  handler.RefreshCalendarParam:
    properties:
      project_key:
        type: string
      work_item_id:
        type: integer
      work_item_type_key:
        type: string
    type: object
  handler.WorkItemMeeting:
    properties:
      bind_operator:
        description: 关联日程操作人(meego 的 userKey)
        type: string
      bind_operator_info:
        allOf:
        - $ref: '#/definitions/handler.MeegoUserInfo'
        description: 关联日程操作人的信息
      calendar_event_app_link:
        description: 日程跳转 APP 链接
        type: string
      calendar_event_desc:
        description: 日程描述(应该是对应的会议描述, 因为会议没有描述)
        type: string
      calendar_event_id:
        type: string
      calendar_event_name:
        type: string
      calendar_event_organizer:
        allOf:
        - $ref: '#/definitions/larkcalendar.EventOrganizer'
        description: 日程组织者
      calendar_event_recurrence:
        type: string
      calendar_id:
        type: string
      meeting_host_user:
        allOf:
        - $ref: '#/definitions/larkvc.MeetingUser'
        description: 会议主持人
      meeting_id:
        description: 会议 ID
        type: string
      meeting_minute_url:
        description: 会议纪要链接(看着openapi接口好像没有)
        type: string
      meeting_participant_count:
        description: 参会峰值人数
        type: string
      meeting_participant_count_accumulated:
        description: 参会累计人数
        type: string
      meeting_record_url:
        description: 会议录制链接
        type: string
      meeting_status:
        description: 会议状态, 可选值 1(呼叫中), 2(进行中) 3(已结束)
        type: integer
      meeting_time:
        allOf:
        - $ref: '#/definitions/handler.MeetingTime'
        description: 会议时间, 都是 unix 时间, 单位 sec
      meeting_topic:
        description: 会议主题
        type: string
      project_key:
        type: string
      work_item_id:
        type: integer
      work_item_type_key:
        type: string
    type: object
  lark_api.SearchCalendarEventRespData:
    properties:
      items:
        description: 搜索命中的日程列表
        items:
          $ref: '#/definitions/larkcalendar.CalendarEvent'
        type: array
      page_token:
        description: 下次请求需要带上的分页标记
        type: string
    type: object
  larkcalendar.CalendarEvent:
    properties:
      app_link:
        description: 日程的app_link,跳转到具体的某个日程
        type: string
      attendee_ability:
        description: 参与人权限
        type: string
      color:
        description: 日程颜色，颜色RGB值的int32表示。仅对当前身份生效；客户端展示时会映射到色板上最接近的一种颜色；值为0或-1时默认跟随日历颜色。
        type: integer
      create_time:
        description: 日程的创建时间（秒级时间戳）
        type: string
      description:
        description: 日程描述；目前不支持编辑富文本描述，如果日程描述通过客户端编辑过，更新描述会导致富文本格式丢失
        type: string
      end_time:
        allOf:
        - $ref: '#/definitions/larkcalendar.TimeInfo'
        description: 日程结束时间
      event_id:
        description: 日程ID。参见[日程ID说明](https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/calendar-v4/calendar-event/introduction)
        type: string
      event_organizer:
        allOf:
        - $ref: '#/definitions/larkcalendar.EventOrganizer'
        description: 日程组织者信息
      free_busy_status:
        description: 日程占用的忙闲状态，新建日程默认为Busy；仅新建日程时对所有参与人生效，之后修改该属性仅对当前身份生效
        type: string
      is_exception:
        description: 日程是否是一个重复日程的例外日程
        type: boolean
      location:
        allOf:
        - $ref: '#/definitions/larkcalendar.EventLocation'
        description: 日程地点
      need_notification:
        description: 更新日程是否给日程参与人发送bot通知，默认为true
        type: boolean
      organizer_calendar_id:
        description: 日程组织者日历ID。参见[日历ID说明](https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/calendar-v4/calendar/introduction)
        type: string
      recurrence:
        description: 重复日程的重复性规则；参考[rfc5545](https://datatracker.ietf.org/doc/html/rfc5545#section-3.3.10)；;-
          不支持COUNT和UNTIL同时出现；;- 预定会议室重复日程长度不得超过两年。
        type: string
      recurring_event_id:
        description: 例外日程的原重复日程的event_id
        type: string
      reminders:
        description: 日程提醒列表
        items:
          $ref: '#/definitions/larkcalendar.Reminder'
        type: array
      schemas:
        description: 日程自定义信息；控制日程详情页的ui展示。
        items:
          $ref: '#/definitions/larkcalendar.Schema'
        type: array
      start_time:
        allOf:
        - $ref: '#/definitions/larkcalendar.TimeInfo'
        description: 日程开始时间
      status:
        description: 日程状态
        type: string
      summary:
        description: 日程标题
        type: string
      vchat:
        allOf:
        - $ref: '#/definitions/larkcalendar.Vchat'
        description: 视频会议信息。
      visibility:
        description: 日程公开范围，新建日程默认为Default；仅新建日程时对所有参与人生效，之后修改该属性仅对当前身份生效
        type: string
    type: object
  larkcalendar.EventLocation:
    properties:
      address:
        description: 地点地址
        type: string
      latitude:
        description: 地点坐标纬度信息，对于国内的地点，采用GCJ-02标准，海外地点采用WGS84标准
        type: number
      longitude:
        description: 地点坐标经度信息，对于国内的地点，采用GCJ-02标准，海外地点采用WGS84标准
        type: number
      name:
        description: 地点名称
        type: string
    type: object
  larkcalendar.EventOrganizer:
    properties:
      display_name:
        description: 日程组织者姓名
        type: string
      user_id:
        description: 日程组织者user ID
        type: string
    type: object
  larkcalendar.MeetingSettings:
    properties:
      allow_attendees_start:
        description: 允许日程参与者发起会议
        type: boolean
      assign_hosts:
        description: 指定主持人
        items:
          type: string
        type: array
      auto_record:
        description: 设置自动录制
        type: boolean
      join_meeting_permission:
        description: 设置入会范围
        type: string
      open_lobby:
        description: 开启等候室
        type: boolean
      owner_id:
        description: 设置会议 owner
        type: string
    type: object
  larkcalendar.Reminder:
    properties:
      minutes:
        description: 日程提醒时间的偏移量，正数时表示在日程开始前X分钟提醒，负数时表示在日程开始后X分钟提醒;新建或更新日程时传入该字段，仅对当前身份生效
        type: integer
    type: object
  larkcalendar.Schema:
    properties:
      app_link:
        description: 按钮点击后跳转的链接; **该字段暂不支持传入。**
        type: string
      ui_name:
        description: 'UI名称。取值范围如下： ;- ForwardIcon: 日程转发按钮 ;- MeetingChatIcon: 会议群聊按钮
          ;- MeetingMinutesIcon: 会议纪要按钮 ;- MeetingVideo: 视频会议区域 ;- RSVP: 接受/拒绝/待定区域
          ;- Attendee: 参与者区域 ;- OrganizerOrCreator: 组织者/创建者区域'
        type: string
      ui_status:
        description: UI项自定义状态。**目前只支持hide**
        type: string
    type: object
  larkcalendar.TimeInfo:
    properties:
      date:
        description: 仅全天日程使用该字段，如2018-09-01。需满足 RFC3339 格式。不能与 timestamp 同时指定
        type: string
      timestamp:
        description: 秒级时间戳，如1602504000(表示2020/10/12 20:0:00 +8时区)
        type: string
      timezone:
        description: 时区名称，使用IANA Time Zone Database标准，如Asia/Shanghai；全天日程时区固定为UTC，非全天日程时区默认为Asia/Shanghai
        type: string
    type: object
  larkcalendar.Vchat:
    properties:
      description:
        description: 第三方视频会议文案，可以为空，为空展示默认文案
        type: string
      icon_type:
        description: 第三方视频会议icon类型；可以为空，为空展示默认icon。
        type: string
      meeting_settings:
        allOf:
        - $ref: '#/definitions/larkcalendar.MeetingSettings'
        description: VC视频会议的会前设置
      meeting_url:
        description: 视频会议URL
        type: string
      vc_type:
        description: 视频会议类型
        type: string
    type: object
  larkvc.MeetingUser:
    properties:
      id:
        description: 用户ID
        type: string
      user_type:
        description: 用户类型
        type: integer
    type: object
info:
  contact: {}
paths:
  /api/v1/lark/calendar/search:
    get:
      description: 根据关键字搜索, 返回的结构信息可以参考 https://open.feishu.cn/document/server-docs/calendar-v4/calendar-event/search
      parameters:
      - in: query
        name: page_size
        type: integer
      - in: query
        name: page_token
        type: string
      - in: query
        name: query_word
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/lark_api.SearchCalendarEventRespData'
      summary: 搜索日程
      tags:
      - calendar
  /api/v1/meego/calendar_event/bind:
    post:
      description: 将日程和实例绑定或者解绑
      parameters:
      - description: 参数
        in: body
        name: OperateCalendarEventWithWorkItemParam
        required: true
        schema:
          $ref: '#/definitions/handler.OperateCalendarEventWithWorkItemParam'
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: 操作日程和 meego 实例
      tags:
      - Plugin
  /api/v1/meego/calendar_event/unbind:
    post:
      description: 将日程和实例解绑
      parameters:
      - description: 参数
        in: body
        name: OperateCalendarEventWithWorkItemParam
        required: true
        schema:
          $ref: '#/definitions/handler.OperateCalendarEventWithWorkItemParam'
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: 操作日程和 meego 实例解绑
      tags:
      - Plugin
  /api/v1/meego/lark/auth:
    get:
      description: 飞书 code 授权登录
      parameters:
      - in: query
        name: code
        type: string
      - in: query
        name: state
        type: string
      responses:
        "302":
          description: Found
      summary: 飞书授权登录
      tags:
      - Plugin
  /api/v1/meego/work_item_meetings:
    post:
      description: 分页获取实例关联的会议
      parameters:
      - in: query
        name: page_number
        type: integer
      - in: query
        name: page_size
        type: integer
      - in: query
        name: project_key
        type: string
      - in: query
        name: work_item_id
        type: integer
      - in: query
        name: work_item_type_key
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.ListWorkItemMeetingsResp'
      summary: 分页获取实例关联的会议
      tags:
      - Plugin
  /api/v1/meego/work_item_meetings/chat_auto_bind:
    get:
      description: 获取群自动关联日程的状态
      parameters:
      - description: 查询某个工作项的自动加群状态
        in: query
        name: work_item_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.GetAutoBindCalendarStatusResp'
      summary: 获取群自动关联日程的状态
      tags:
      - Plugin
    post:
      description: 群自动关联日程
      parameters:
      - description: 参数
        in: body
        name: ChatAutoBindCalendarParam
        required: true
        schema:
          $ref: '#/definitions/handler.ChatAutoBindCalendarParam'
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.ErrMsgResp'
      summary: 群自动关联日程
      tags:
      - Plugin
  /api/v1/meego/work_item_meetings/refresh:
    post:
      description: 刷新工作项关联的会议最新信息
      parameters:
      - description: 参数
        in: body
        name: RefreshCalendarParam
        required: true
        schema:
          $ref: '#/definitions/handler.RefreshCalendarParam'
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: 刷新工作项关联的会议最新信息
      tags:
      - Plugin
  /api/v1/ping:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: 测试 ping, 任何请求方式都可以
      tags:
      - test
swagger: "2.0"
